# Test your FastAPI endpoints
PUT http://127.0.0.1:8000/api/user/profile/00000000-0000-0000-0000-000000000000/cape
Authorization: Bearer LoOKslIkeAjWt
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pack.png"

not image
--WebAppBoundary--

###
DELETE http://127.0.0.1:8000/api/user/profile/00000000-0000-0000-0000-000000000000/cape
Authorization: Bearer LoOKslIkeAjWt

###
DELETE http://127.0.0.1:8000/api/user/profile/00000000-0000-0000-0000-000000000000/cape

###